### ISSUE TITLE
Recursive enums lose path information

### ISSUE THREAD

**Issue by mythmon** [dtolnay/path-to-error#14] opened 2021-10-26 21:10 UTC
This may be similar to #6 and #9.

When deserializing an enum that can recursively hold itself, like this:

```rust
enum Thing {
    Foo {
        inner: Option<Box<Thing>>,
        required_field: u32,
    },
    Bar,
}
```

The path returned for errors is `.` (a dot).

Both of these JSON strings returns the same error:

```json
{
    "type": "Foo",
    "required_field": 1,
    "inner": {
        "type": "Foo",
        "inner": null
    }
}
```

```json
{
    "type": "Foo",
    "inner": {
        "type": "Foo",
        "required_field": 2,
        "inner": null
    }
}
```

The first is missing `required_field` at the second level, and the second is missing at the top level. It is impossible to tell from the error where the problem is. The `Display` of the error is

```
.: missing field `required_field`
```

Full code to reproduce is here: https://gist.github.com/mythmon/e29581a739bdbbee237df11b39213d22

**Comment by christos-h** [comment] 2021-11-16 01:38
If someone could point me in the right direction here I can take a shot at the fix.

**Comment by dtolnay** [comment] 2023-03-04 23:56
Closing as a duplicate of #1.

**Closed as completed** 2023-03-04 23:57 UTC
